apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-kubernetes
  namespace: banking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-cloud-kubernetes-role
  namespace: banking
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-kubernetes-rolebinding
  namespace: banking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-cloud-kubernetes-role
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes
    namespace: banking